# Generated by Django 3.2.7 on 2021-10-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='info',
        ),
    ]
