# Generated by Django 3.2.7 on 2021-10-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100, verbose_name='ToDo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=18, verbose_name='ユーザー名')),
            ],
        ),
        migrations.CreateModel(
            name='TimerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_name', models.CharField(max_length=18, verbose_name='タイマー名')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_order', models.IntegerField(verbose_name='インターバルタイマー順番')),
                ('interval_second', models.IntegerField(verbose_name='インターバルタイマー秒数')),
                ('timer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.timertable')),
            ],
        ),
    ]
