# Generated by Django 3.2.7 on 2021-10-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userinfo_info'),
        ('todo', '0002_auto_20211005_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timertable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo'),
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
