# Generated by Django 3.2.7 on 2021-10-06 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userinfo_info'),
        ('todo', '0003_auto_20211005_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervaltable',
            name='timer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_table', to='todo.timertable'),
        ),
        migrations.AlterField(
            model_name='timertable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_table', to='users.userinfo'),
        ),
    ]
